### ISSUE TITLE
Completion of non standard package?

### ISSUE THREAD

**Issue by vbauerster** [zchee/deoplete-go#61]
I have code with external package import:

```
package main

import "gopl.io/ch4/github"

func main() {
    github.|
}
```

But there is no completion appears after I type `github.|` (pipe is cursor position).
Is it supposed to complete external packages at all? At the moment it does not.
If yes, could you please advise, what needs to be done in order to enable external package completion?
Here is my config:

```
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])

let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
let g:deoplete#sources#go#use_cache = 1
let g:deoplete#sources#go#json_directory = $HOME.'/.config/nvim/plugged/deoplete-go/data/json/1.6.2/darwin_amd64'
```

**Comment by kevin70** [comment]
me too.

`let g:deoplete#enable_at_startup = 1

let g:deoplete#sources#go#gocode_binary = '/Users/kevin/.go/bin/gocode'
let g:deoplete#sources#go#package_dot = 1
let g:deoplete#sources#go#use_cache = 1
let g:deoplete#sources#go#json_directory = '/Users/kevin/.cache/deoplete/go/darwin_amd64'
`

**Comment by zchee** [comment]
@vbauerster @weghst Hi, thanks issue :)

Maybe, this problem caused by `gocode` original behavior. (and not issue, it's gocode normal behavior.)
If there `import ***` word in your code, `gocode` will parse `***.a` file such as `$GOPATH/pkg/darwin_amd64/gopl.io/ch4/github.a`
So, If you want to complete of `gopl.io/ch4/github` method, needs `go install gopl.io/ch4/github` only at first.

I was tested that flow, and it will work :)
Could you try it?

**Comment by vbauerster** [comment]
@zchee You are right, a custom package needs to be installed first, before it can be referenced by `gocode`. So after I run `go install gopl.io/ch4/github`, completion of the package started to work properly.
Thanks, for your valuable note!
I assume the issue may be closed now)

**Comment by Shougo** [comment]
Closed.
