### ISSUE TITLE
Bad completion behaviour without a "omni_pattern" like feature

### ISSUE THREAD

**Issue by svanharmelen** [zchee/deoplete-go#7]
The default behaviour you get when using `deoplete.nvim` with an `omni_pattern` for autocompleting Go code, was that the autocompletion would not start before you typed in the second character of a word.

This is because the default value of `g:deoplete#auto_completion_start_length` is set to 2. So if I would type `fm` it would now suggest `fmt`. This is perfectly fine and good behaviour, but now it's gone using this plugin.

Now as soon as I change to `INSERT` mode, I get a whole list with completions, without even typing 1 single character:

![example1](https://cloud.githubusercontent.com/assets/4171547/12386238/530a7686-bdc4-11e5-80b3-b72102ee30fb.gif)

As you can see I don't type anything, I just switch between `INSERT` and `NORMAL` mode and that gives me (unwanted) autocompletion suggestions. Now I know I can change this behaviour by setting `call deoplete#custom#set('go', 'min_pattern_length', 2)` which then gives me the old behaviour again:

![example2](https://cloud.githubusercontent.com/assets/4171547/12386427/ccc64a44-bdc5-11e5-9ccf-a0a1ead32372.gif)

As you can see, this time switching modes doesn't trigger autocompletion, so I only get a suggestion when typing at least 2 characters (`fm` in this example).

So you would think things are good now, but they are not. Because now it doesn't complete again after typing a dot `.` until you again typed at least 2 characters :disappointed: :

![example3](https://cloud.githubusercontent.com/assets/4171547/12386528/725d65d2-bdc6-11e5-9390-7ff611afaf74.gif)

As you can see now, I only get the second completion after typing `fmt.Pr` which is not what you want and expect.

So now I switched back to just using `deoplete.nvim` again by disabling the `deoplete-go` plugin and adding `g:deoplete#omni_patterns.go = '[^. *\t]\.\w*'` to my `init.nvim`. This now restores the desired behaviour:

![example4](https://cloud.githubusercontent.com/assets/4171547/12386678/8e91ca4e-bdc7-11e5-9a56-961378dea5f9.gif)

As you can see, this time I do not get suggestions when switching between `INSERT` and `NORMAL` mode, but only after typing 2 characters (`fm`) I get the first suggestion. When I then continue and type the dot `.` I immediately get a list with additional suggestions.

Now I know that I actually get two different types of completion here. The first completion (for the `fm` part) was a `buffer` completion triggered by `g:deoplete#auto_completion_start_length`. And the second one (for the `fmt.` part) was the actual `omni` completion triggered by matching the `g:deoplete#omni_patterns.go` pattern.

I think this is a very common and desired way of using the autocompletion, but currently I don't think this plugin offers this kind of behaviour. So I think that this plugin should be made a little bit smarter so it can have both a `min_pattern_length` _and_ a `omni_pattern` which can both trigger the completion when either one of the configured values (either the length or the pattern) is matched.

Thanks!

/ping @shougo

**Comment by Shougo** [comment]
Yes, it is deoplete-go's problem.
Deoplete-go's min_pattern_length is 0, so deoplete-go should check keyword pattern in the source.

**Comment by svanharmelen** [comment]
EDIT: @shougo I understand... If `deoplete-go` would only use a pattern like the `omni` completion does, it would have the same behaviour. In that case again the `buffer` completion would kick in after typing 2 characters and then the `deoplete-go` completion would kick in when the pattern was matched after typing `fmt.`

So what needs to be changed? Should this line be removed https://github.com/zchee/deoplete-go/blob/master/rplugin/python3/deoplete/sources/go.py#L12 (I believe so) and a few new lines be added that use (or add) a pattern that is then used to trigger on?

**Comment by zchee** [comment]
@svanharmelen Thanks issue :)

but, I do not understand all. Sorry.
If you have time, Could you answer the question for me?

# 

All examples of the fmt package.
And please forget omnifunc, I want to know the operation to your desired.
1. Do you **not** want to open `popupmenu` immediately after the insert mode?
2. Do you want to word suggestions after typing `2` char?
3. Do you want to suggestion of `fmt` when you typed `ft`?
4. Do you want to pkg of func not need type dot`.`?

# 

Now, I understand In this context.
You want to suggest Go stdlib pkg also imported pkg **name** after 2 type char.
but, you want to suggests that pkg of **func** not need dot`.`, also want the insertion of dot`.` and open `popupmenu` in automatically.
And, that pkg of **func** **not need** `2` type char.

It correct?

**Comment by zchee** [comment]
@svanharmelen And,
Do you want to suggestion the **name** of the pkg to buffer rather than deoplete-go?

**Comment by svanharmelen** [comment]
Not sure if I can follow you (I'm having trouble reading/understanding your english), but here goes...
1. No, I do not want the popupmenu to open immidiately after switching to insert mode
2. Yes, I would like to start completion after typing the 2nd character
3. Yes, after 'fm' or 'ft' (after typing 2 characters)
4. I do want to type the . myself

Maybe you can look to the examples again. I want the behaviour like shown in the last example.

@shougo I believe you understand exactly what behaviour I want, maybe you could help translate here as I believe my previous post was about as detailed as it could be.

Thanks!

**Comment by svanharmelen** [comment]
Also, this is not limited to Go stdlib packages, it general behaviour.

It would be fine to get pkg completions from either the buffer or deoplete-go (guess deoplete-go would be nicer to have) as long as completions after the . are called immediately and before the . after two charaters.

Does this help?

**Comment by zchee** [comment]
@svanharmelen Thanks reply.
Sorry, I not good at English.. :(

>  I want the behaviour like shown in the last example.

I understand.
Currently `min_pattern_length` affects for both pkg name(or parent of struct) and func(or child of struct)

# 

If 

``` vim
let g:deoplete#auto_completion_start_length = 2
" customize `deoplete-go` default  value
call deoplete#custom#set('go', 'min_pattern_length', 2)
```

 suggests `func` (or child of struct) also need `2` type char. You do not want it.

# 

If

``` vim
let g:deoplete#auto_completion_start_length = 2
" comment out. use deoplete-go` default value
" call deoplete#custom#set('go', 'min_pattern_length', 2)
```

but `deoplete-go` would ignore the `g:deoplete#auto_completion_start_length` setting.
`deoplete-go` it will open a `popupmenu` after `1` typed char. You do not want it too.

# 

If

``` vim
let g:deoplete#auto_completion_start_length = 0
call deoplete#custom#set('go', 'min_pattern_length', 2)
```

`deoplete` it will open the popup after `2` typed char, OK.
but `deoplete-go` not works. There is only a `member` or `buffer` to the completion list.

# 

So, You want the split `min_pattern_length` settings for parent and child.
Or, `deoplete-go` monitors the dot, and to change the dynamically set when dots are typed.
Correct?

# 

Sorry long comments...
This problem is I want to also improve.
Please bear until I understand :(

**Comment by svanharmelen** [comment]
@zchee thanks for the update and no worries, your English is still much, much better then my Japanese will ever be :wink:

Your latest update is correct. In the `deoplete.nvim` package the `omni` completion source is only triggered based on a pattern (regex) and until something matches that pattern, the length is used to trigger the other completion (e.g. buffer, file) sources.

So I think that `deoplete-go` should have 2 possible triggers:
1. Trigger based on a certain length;
2. Trigger based on a certain pattern;

Currently only the first trigger exists, but I think the second trigger is much more important. If we have the second pattern based trigger, `deoplete-go` would behave the same as the `omni` completion source currently does when used within `deoplete.nvim`.

**Comment by zchee** [comment]
@svanharmelen 

> your English is still much, much better then my Japanese will ever be :wink:

Thanks :sob: 

I explainted issue and discussed with Shougo, The results reached is this.

Now, `deoplete.nvim` have not split setting of `min_pattern_length` for parent and child.
This is specification of deoplete.
but, Shougo said "This problem will also occur in the other sources plugin, So this problem is solved by implementing in the deoplete core."

We will wait for implemented of deoplete.

**Comment by svanharmelen** [comment]
Check! That makes good sense... I'll keep an eye on the deoplete.nvim repo for any fixes/changes in there and will test them as they are added.

**Comment by fatih** [comment]
Hi everyone. I've just was trying deoplete as I have enough now calling `c-x c-o` manually :) So it's time to go back and use one of the completions plugin. Fortunately @zchee pointed me to this and I had good memories with @Shougo's deoplete plugin and I gave a try. 

So completion is a tricky topic as it changes a lot based on the user preference. Some prefer completion to change via `tab`, others via `c-n` , etc.. Some prefer to complete the suggesion as soon as they type, some prefer enter, etc.. Fortunately these can be fixed because `deoplete` provides a lot of functions for these. And I already adapted them.

But when it comes to understanding the source code it's a little bit tricky. So my problem was basically just this: 

<img width="342" alt="image 2016-01-19 at 11 39 25 pm" src="https://cloud.githubusercontent.com/assets/438920/12440350/b0fe3814-bf08-11e5-81c9-92e768958fd1.png">

I wanted that it doesn't complete in a comment, or say after `0` length pattern. But I've solved my problem with the following three lines:

```
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.go = '[^. *\t]\.\w*'
call deoplete#custom#set('go', 'min_pattern_length', 1)
```

For now it's just works for me. I wonder however if this is not enough. @svanharmelen is this not solving your problem actually? I mean what other cases might be that would be problematic? I've tried to understand it from your first comment but was lost :/

**Comment by fatih** [comment]
Ok just using it a little bit, for example it shouldn't trigger inside comment's at all.

**Comment by svanharmelen** [comment]
@fatih by setting the `omni` pattern, you actually fall back to using the old style completion where `deoplete.nvim` calls `omni` which calls `vim-go` which calls `gocode`. You can see the difference by the completions itself. If it doesn't show `[go]` at the end, it means it's not completed by `deoplete-go`, but by `deoplete.nvim`.

So with these settings packages are completed just fine by `deoplete-go`, but after typing a `.` to use or call anything inside the package, you fall back to the old behaviour. Indeed this is a way to work around the problem for now, but it's not the solution.

But as far as I understood @Shougo is in the know and understands the issue which he wants to solve in `deoplete.nvim` so any other future source plugins don't have to all fix this themselves. So I'm currently waiting for any updates from @Shougo on this one...

As for the completions inside comments... I love the `buffer` source completion in there, but indeed (IMO) it should not do `Go` completion inside comments.

Thanks!

**Comment by zchee** [comment]
@svanharmelen Thanks for the detailed explanation :) That's right.
I did not have the confidence to be described detail in English...

@fatih Thanks issue and thanks for testing in response to my twitter mention :)

The advantage of `deoplete.nvim` and `deoplete-go`, Can get a completion word dictionary with  non blocking user interface use the `msgpack-rpc` also `neovim/python-client`.
`deoplete.nvim` that can call the `omnifunc` it is for backwards compatibility. `deoplete.nvim` do not like the `omnifunc`.
See also
- https://github.com/Shougo/deoplete.nvim/blob/master/doc%2Fdeoplete.txt#L174-L175
- https://github.com/zchee/deoplete-go#why-deoplete-also-deoplete-go-are-not-use-omnifunc
- https://github.com/zchee/deoplete-go/issues/4#issuecomment-172412821

> As for the completions inside comments... I love the buffer source completion in there, but indeed (IMO) it should not do Go completion inside comments.

Yes. If not use `deoplete-go`, maybe(not tested) also displayed `buffer`, `snip` and `tag` completion word.
This problem is not related to this mater(this thread).
I will consider for this problem.
If you do not want to display the only `Go` ([go]) completion, can be improve inside of `deoplete-go`.

**Comment by Shougo** [comment]
@zchee Hi, I have added `input_pattern` feature.   Deoplete-go should use it instead of min_pattern_length.

**Comment by zchee** [comment]
@Shougo Thanks!!
I will update later.

Is this correct?

``` python
        self.input_pattern = '[^. \t0-9]\.\w*'
```

**Comment by zchee** [comment]
@svanharmelen @fatih 
I created pul-request.
Could you test it?

https://github.com/zchee/deoplete-go/pull/8

**Comment by zchee** [comment]
Close.
See https://github.com/zchee/deoplete-go/pull/8.
