### ISSUE TITLE
Inconsistent completion, when json cache enabled

### ISSUE THREAD

**Issue by vbauerster** [zchee/deoplete-go#79]
Completion without json cache: (expected one)
![no cache](https://s25.postimg.org/e2hcv2wr3/Screen_Shot_2016_10_25_at_15_52_29.png)

Completion with json cache enabled: (unexpected one)
![with cache](https://s25.postimg.org/hktcrgxn3/Screen_Shot_2016_10_25_at_15_53_35.png)

**Comment by zchee** [comment]
@vbauerster ah, it's normal behavior. because Go stdlib have two `scanner` package.
so, deoplete-go will return the "mixed" two methods.
If parse all of `import` section, will return the correct method. but I was sloppy implementation.

BTW, gocode already have "no imported package completion". so I consider remove json cache feature on deoplete-go.

Well, sorry for confused you. that's no a bug :(

**Comment by zchee** [comment]
xref: https://github.com/zchee/deoplete-go/issues/70#issuecomment-260104611

**Comment by vbauerster** [comment]
@zchee Thank you, I see now. Yes I've noticed, that gocode has the feature already. Gocode authors were inspired by your plugin, most probably ;)

**Comment by zchee** [comment]
@vbauerster 

> Gocode authors were inspired by your plugin, most probably ;)

If so, I am extremely glad :D
I also maintain the gocode that for the go devel version support if possible. Also I will do my best to it :)
