### ISSUE TITLE
How to compile if not using one of the named plugin managers?

### ISSUE THREAD

**Issue by Integralist** [zchee/deoplete-go#97]
Hello,

I use https://github.com/airblade/voom as my vim plugin manager, it's a very simple shell script for managing vim plugins (so no fancy post-load functions like the other plugin managers you've detailed in the README).

How would I compile the C bindings ([mentioned here](https://github.com/zchee/deoplete-go#4-install-plugin-and-build-ujson-module))?

I've already `pip install ujson` separately, so is that enough or do I need to actually compile something for deoplete-go to work?

**Comment by zchee** [comment]
@Integralist Hi, thanks for creating the issue.

> How would I compile the C bindings (mentioned here)?

Just `cd /path/to/deoplete-go` and `make` command. Maybe successful compile `ujson` C module.

> I've already pip install ujson separately, so is that enough or do I need to actually compile something for deoplete-go to work?

To be clear, use `ujson` module for performance. I'd wrote fallback use stdlib json module at [rplugin/python3/deoplete/sources/deoplete_go.py#L15-L19](https://github.com/zchee/deoplete-go/blob/9c2d57710f022ea5fe3b0428e6635a3de77bcf9e/rplugin/python3/deoplete/sources/deoplete_go.py#L15-L19)
So, if you doesn't  compile with `make,` actually not installed submodules `ujson`, use stdlib json module and deoplete-go would work fine.
Also, deoplete-go is normal Python3 code. So yeah, if you already installed `ujson` on system global, deoplete-go using that module but haven't version lock (for ujson).

Anyway, use `ujson` are very small optimization because gocode output json is small.
